import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navigation bar */}
        <nav>
          <ul>
            <li>Home</li>
            <li>Colleges</li>
            <li>Admission</li>
            <li>My College</li>
          </ul>
        </nav>
        {/* main content */}
        <main className="h-screen">{children}</main>
        {/* footer */}
        <footer className="bg-gray-100 text-center p-4 text-black">
          College of Engineering and Technology, University of Dar es Salaam
        </footer>
      </body>
    </html>
  );
}
